### ISSUE TITLE
card number is not protected

### ISSUE THREAD

**Issue by mgeng20** [5500-project/opp-api#12]
When a transaction is processed, the message is displaying the whole credit/debit card number
<img width="468" alt="Pasted Graphic 2" src="https://github.com/5500-project/opp-api/assets/133167392/9fa6bcb8-7005-484f-95d6-995d3cc38c6e">

Credit card or debit card number is expected to be protected and hidden for security purpose and only the last four digits may be displayed

**Comment by lby-rgyyt** [comment]
Thank you for your feedback, we have fixed this issue.
