### ISSUE TITLE
Do not check the password length and Email, Phone number validation

### ISSUE THREAD

**Issue by YuxuanRen0816** [5500-project/opp-api#13]
**To Reproduce**
Go to 'Signup'
Fill out'Email, Phone number with only 1 digit'
Do not have hint 

**Expected behavior**: Have a hint to the customer to  to input valid Email and Phone

**Screenshots**
![Image 2023-12-07 at 7 25 PM](https://github.com/5500-project/opp-api/assets/133261619/325d8879-1da8-47de-a682-3f9d1d682d7e)

**Comment by Lenalu98** [comment]
Fixed. Thank you!
