### ISSUE TITLE
spam risk

### ISSUE THREAD

**Issue by mgeng20** [5500-project/opp-api#14]
**Describe the bug**
when processing a transaction, if the user clicks the "next" button multiple times in a very short time by accident, multiple transactions are processed on the same card for the same amount.

<img width="447" alt="Pasted Graphic 3" src="https://github.com/5500-project/opp-api/assets/133167392/4547199b-7d02-480d-aba3-5e6b2e00cdfe">

**Expected behavior**
System should prevent repeated data submission

**Comment by Lenalu98** [comment]
Fixed! Thank you.
