### ISSUE TITLE
Invalid transaction amount like "000X" also work

### ISSUE THREAD

**Issue by YuxuanRen0816** [5500-project/opp-api#15]
**Describe the bug**
Invalid transaction amount like "000X" also work

**To Reproduce**
Go to ' Make Transaction'
Click on 'Amount as 00009'
See Payment Successfully

**Expected behavior**
To have an error hint when customer input invalid amount

**Screenshots**
<img width="486" alt="Screenshot 2023-12-07 at 7 07 55 PM" src="https://github.com/5500-project/opp-api/assets/133261619/64196caf-250d-44e8-90f8-1f1729d09ac9">

**Comment by lby-rgyyt** [comment]
Thank you for your feedback, we have fixed this issue.
