### ISSUE TITLE
Negative amount also work

### ISSUE THREAD

**Issue by YuxuanRen0816** [5500-project/opp-api#16]
**Describe the bug**
Negative amount also work

**Expected behavior**
Error hint when customer input negative amount

**Screenshots**
<img width="1075" alt="Screenshot 2023-12-07 at 7 36 09 PM" src="https://github.com/5500-project/opp-api/assets/133261619/8dfdcd5f-185d-43fe-9458-473a0ede8ad3">

**Comment by lby-rgyyt** [comment]
Thank you for your feedback, we have fixed this issue.
