### ISSUE TITLE
$0 transaction gets processed

### ISSUE THREAD

**Issue by mgeng20** [5500-project/opp-api#17]
**Describe the bug**
When user put $0 as the amount, the transaction still gets processed

**Expected behavior**
The system is expected to process any amount greater than $0.

**Screenshots**
<img width="438" alt="Pasted Graphic 7" src="https://github.com/5500-project/opp-api/assets/133167392/02d221be-ec0c-4771-a895-a91c3291da62">

**Comment by lby-rgyyt** [comment]
Thank you for your feedback, we have fixed this issue.
